### ISSUE TITLE
the Software wont load

### ISSUE THREAD

**Issue by ezemania2** [ShadiestGoat/DiscordChatExporter#11]
I got this error and don't realy endernstand my he doesn't want to load
![image](https://user-images.githubusercontent.com/81659486/191845946-3106b49e-b5f5-4e27-9a23-2dd5251846fe.png)

**Comment by ShadiestGoat** [comment]
Hello! I believe #6bf18a8 fixes this.

**Comment by ShadiestGoat** [comment]
(v0.3.2 is in the releases now)
