### ISSUE TITLE
[BUG] Doesn't support discord's new length IDs

### ISSUE THREAD

**Issue by maplefluff** [ShadiestGoat/DiscordChatExporter#13]
**Before submitting this bug, please check the following:**

- [-] I have checked issues, and could not find a similar one
- [-] I am on the latest version of DiscordChat exporter
- [-] I have read the relevant wiki pages

**Describe the bug**

Cuts off the last character of Discord IDs, keeping them at 18 digits in length. This only applies to new Discord IDs, 17 and 18 digit ones still work fine

**To Reproduce**

1. Find a channel with an ID that is 19 digits in length, or make a new channel
2. Run the exporter on that channel
3. Watch as it cuts off one digit

**Expected behavior**
Script should still accept 19 digit IDs instead of cutting off the last digit

**Screenshots**

![image](https://user-images.githubusercontent.com/72973369/196248460-a5205e0d-0047-4608-a60c-b74f78fd9e28.png)
![image](https://user-images.githubusercontent.com/72973369/196248539-37829fa3-01f8-40db-b670-ffcfbf4f8582.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2

**Comment by Haelikor** [comment]
Hey, if you build from source and modify:
`var snowflakeVarifyReg = regexp.MustCompile(`\d{18}`)` to instead be 19, it works. However it'll then fail for the 18 variant.

I'm not too good with this so my lazy solution was to go build one with 18 and one with 19. lol Hope I helped in the meantime.

**Comment by ShadiestGoat** [comment]
Hello! This should be fixed with [3c50541](https://github.com/ShadiestGoat/DiscordChatExporter/commit/3c50541f7f257f82910f10dbfca275f80f5f90c3)
