### ISSUE TITLE
[SECURITY]: Add more headers

### ISSUE THREAD

**Issue by bytixo** [ShadiestGoat/DiscordChatExporter#9]
Adding some required headers could make the fetching behavior more "legit".

It is known that discord use some headers for fingerprinting, and not providing those _might_ flag an account (`only a supposition but we are never too safe`)

Here's an example of a "safe" request
https://gist.github.com/bytixo/4d70d5711add2685e2bbd36dc99b203c

These headers are somewhat the same for all the requests.

Note that the cookies are like a session, you instantiate a new cookie jar to your http.Client, make the request to `https://discord.com` and you are good to go

Will try to write an implementation for this.

**Comment by ShadiestGoat** [comment]
Hey, thanks for bringing this up, I'll look into it ^^

**Comment by ShadiestGoat** [comment]
Checkout c7e6a58, I've added some of the headers, almost done with this.

**Comment by ShadiestGoat** [comment]
Heya! I'm working on auto pulling all the information atm, but I need help. Im trying to find where discord stores it's build number:

![image](https://user-images.githubusercontent.com/48590492/150217374-a43ffd4e-6fd9-4837-8adf-401aa7a2e4e6.png)

Can you help me find it's location? 

Thank you in advance!

**Comment by ShadiestGoat** [comment]
Nevermind, its all good, check out 7ada1c80112eedf3131dad0139f7a567095e3362 :)
